#!/usr/bin/env bash
# AWP RootNet — API Service one-click deploy
#
# Reads contract addresses from deploy.sh output (api/.env) + extra config from api/.env.local,
# builds Go binaries, initializes DB, and starts all 3 services (api / indexer / keeper).
#
# Prerequisites:
#   - go 1.26+
#   - psql (for DB init)
#   - redis-cli (for health check)
#   - api/.env generated by scripts/deploy.sh
#
# Usage:
#   ./scripts/deploy-api.sh                     # Build + DB init + start all services
#   ./scripts/deploy-api.sh --build-only        # Build binaries only
#   ./scripts/deploy-api.sh --db-only           # Init DB only
#   ./scripts/deploy-api.sh --start             # Start services (assumes already built)
#   ./scripts/deploy-api.sh --stop              # Stop running services
#   ./scripts/deploy-api.sh --status            # Check service status
#
# Config:
#   api/.env          — generated by scripts/deploy.sh (contract addresses, RPC, deploy block)
#   api/.env.local    — manual overrides (DB, Redis, keeper/relayer keys) — not committed

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
API_DIR="$ROOT_DIR/api"
BIN_DIR="$API_DIR/bin"
PID_DIR="$API_DIR/.pids"
LOG_DIR="$API_DIR/logs"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
step()  { echo -e "${CYAN}[STEP]${NC} $*"; }

# ─── Load env ───

load_env() {
    if [[ ! -f "$API_DIR/.env" ]]; then
        error "Missing $API_DIR/.env — run scripts/deploy.sh first to deploy contracts"
    fi
    set -a
    source "$API_DIR/.env"
    # .env.local overrides (DB credentials, private keys, etc.)
    [[ -f "$API_DIR/.env.local" ]] && source "$API_DIR/.env.local"
    set +a
}

# ─── Validate env ───

validate_env() {
    local required=(
        DATABASE_URL REDIS_URL RPC_URL
        ROOTNET_ADDRESS AWP_TOKEN_ADDRESS AWP_EMISSION_ADDRESS
        STAKING_VAULT_ADDRESS STAKE_NFT_ADDRESS SUBNETNFT_ADDRESS
        DAO_ADDRESS TREASURY_ADDRESS DEPLOY_BLOCK
    )
    local missing=()
    for var in "${required[@]}"; do
        [[ -n "${!var:-}" ]] || missing+=("$var")
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Missing required env vars: ${missing[*]}"
    fi
}

# ─── Build ───

do_build() {
    step "Building Go binaries..."
    cd "$API_DIR"
    mkdir -p "$BIN_DIR"
    go build -o "$BIN_DIR/api"     ./cmd/api     &
    go build -o "$BIN_DIR/indexer" ./cmd/indexer  &
    go build -o "$BIN_DIR/keeper"  ./cmd/keeper   &
    wait
    info "Built: $BIN_DIR/{api,indexer,keeper}"
}

# ─── Database ───

do_db() {
    step "Initializing database..."

    if ! command -v psql >/dev/null 2>&1; then
        error "psql not found. Install: apt install postgresql-client"
    fi

    # Test connection
    if ! psql "$DATABASE_URL" -c "SELECT 1" >/dev/null 2>&1; then
        error "Cannot connect to database: $DATABASE_URL"
    fi

    # Create tables
    psql "$DATABASE_URL" -f "$API_DIR/internal/db/schema.sql" 2>/dev/null || info "Schema already exists"

    # Set indexer start block
    local start_block=$((DEPLOY_BLOCK - 1))
    psql "$DATABASE_URL" -c "
        INSERT INTO sync_states (contract_name, last_block)
        VALUES ('indexer', $start_block)
        ON CONFLICT (contract_name) DO NOTHING;
    " 2>/dev/null

    local current_block
    current_block=$(psql "$DATABASE_URL" -t -c "SELECT last_block FROM sync_states WHERE contract_name = 'indexer'" 2>/dev/null | tr -d ' ')
    info "Database ready. Indexer will resume from block ${current_block:-$start_block}"
}

# ─── Start/Stop services ───

do_start() {
    step "Starting services..."
    mkdir -p "$PID_DIR" "$LOG_DIR"

    # Check Redis
    if command -v redis-cli >/dev/null 2>&1; then
        local redis_host redis_port
        redis_host=$(echo "$REDIS_URL" | sed -n 's|.*://\([^:]*\):.*|\1|p')
        redis_port=$(echo "$REDIS_URL" | sed -n 's|.*:\([0-9]*\)/.*|\1|p')
        if ! redis-cli -h "${redis_host:-localhost}" -p "${redis_port:-6379}" ping >/dev/null 2>&1; then
            warn "Redis not reachable at $REDIS_URL"
        fi
    fi

    # Start each service
    start_service "api"     "$BIN_DIR/api"
    start_service "indexer" "$BIN_DIR/indexer"

    if [[ -n "${KEEPER_PRIVATE_KEY:-}" ]]; then
        start_service "keeper" "$BIN_DIR/keeper"
    else
        warn "KEEPER_PRIVATE_KEY not set — keeper service skipped"
    fi

    echo ""
    do_status
}

start_service() {
    local name="$1" bin="$2"
    local pid_file="$PID_DIR/$name.pid"
    local log_file="$LOG_DIR/$name.log"

    # Check if already running
    if [[ -f "$pid_file" ]] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
        warn "$name already running (PID $(cat "$pid_file"))"
        return
    fi

    if [[ ! -x "$bin" ]]; then
        error "$bin not found. Run with --build-only first."
    fi

    nohup "$bin" >> "$log_file" 2>&1 &
    echo $! > "$pid_file"
    info "$name started (PID $!) → $log_file"
}

do_stop() {
    step "Stopping services..."
    for name in api indexer keeper; do
        local pid_file="$PID_DIR/$name.pid"
        if [[ -f "$pid_file" ]]; then
            local pid
            pid=$(cat "$pid_file")
            if kill -0 "$pid" 2>/dev/null; then
                kill "$pid"
                info "$name stopped (PID $pid)"
            else
                info "$name not running (stale PID $pid)"
            fi
            rm -f "$pid_file"
        fi
    done
}

do_status() {
    echo "  Service Status:"
    echo "  ───────────────"
    for name in api indexer keeper; do
        local pid_file="$PID_DIR/$name.pid"
        if [[ -f "$pid_file" ]] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
            echo -e "  $name:    ${GREEN}running${NC} (PID $(cat "$pid_file"))"
        else
            echo -e "  $name:    ${RED}stopped${NC}"
        fi
    done

    # Health check
    local addr="${HTTP_ADDR:-:8080}"
    local port="${addr##*:}"
    if curl -sf "http://localhost:${port}/api/health" >/dev/null 2>&1; then
        echo -e "  health:  ${GREEN}OK${NC} (http://localhost:${port}/api/health)"
    else
        echo -e "  health:  ${YELLOW}unreachable${NC}"
    fi
    echo ""
}

# ─── Print summary ───

print_summary() {
    local addr="${HTTP_ADDR:-:8080}"
    local port="${addr##*:}"
    echo ""
    echo "════════════════════════════════════════════════"
    echo "  AWP RootNet API Deployment Complete"
    echo "════════════════════════════════════════════════"
    echo ""
    echo "  Endpoints:"
    echo "  ──────────"
    echo "  REST API:     http://localhost:${port}/api"
    echo "  Health:       http://localhost:${port}/api/health"
    echo "  Registry:     http://localhost:${port}/api/registry"
    echo "  WebSocket:    ws://localhost:${port}/ws/live"
    [[ -n "${RELAYER_PRIVATE_KEY:-}" ]] && \
    echo "  Relay:        http://localhost:${port}/api/relay/{register,bind}"
    [[ -n "${ALPHA_FACTORY_ADDRESS:-}" && -n "${VANITY_RULE:-}" && "${VANITY_RULE:-0}" != "0" ]] && \
    echo "  Vanity:       http://localhost:${port}/api/vanity/compute-salt"
    echo ""
    echo "  Config:       $API_DIR/.env"
    echo "  Logs:         $LOG_DIR/{api,indexer,keeper}.log"
    echo "  PIDs:         $PID_DIR/{api,indexer,keeper}.pid"
    echo ""
    echo "  Commands:"
    echo "  ─────────"
    echo "  Stop:     ./scripts/deploy-api.sh --stop"
    echo "  Status:   ./scripts/deploy-api.sh --status"
    echo "  Logs:     tail -f $LOG_DIR/api.log"
    echo "════════════════════════════════════════════════"
}

# ─── Main ───

case "${1:-}" in
    --build-only)
        load_env
        do_build
        ;;
    --db-only)
        load_env
        validate_env
        do_db
        ;;
    --start)
        load_env
        validate_env
        do_start
        ;;
    --stop)
        do_stop
        ;;
    --status)
        load_env 2>/dev/null || true
        do_status
        ;;
    --help|-h)
        head -25 "$0" | grep '^#' | sed 's/^# \?//'
        ;;
    "")
        load_env
        validate_env
        do_build
        do_db
        do_start
        print_summary
        ;;
    *)
        error "Unknown flag: $1. Use --help for usage."
        ;;
esac
